### ISSUE TITLE
Cmdlet Collision with Az.Accounts for Resolve-Error (fixit)

### ISSUE THREAD

**Issue by bmkaiser** [PowerShell/AIShell#200]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

When I try to run `Resolve-Error` or its alias `fixit`, the results are not sent to AI Shell. This is happening because the `Az.Accounts` module is already loaded as a prerequsite for the `Az.Tools.Predictor` module, which has an alias named `Resolve-Error` for the `Resolve-AzError` cmdlet.

```powershell
> Get-Command -Name Resolve-Error -All

CommandType Name          Version Source
----------- ----          ------- ------
Alias       Resolve-Error 3.0.2   Az.Accounts
Cmdlet      Resolve-Error 0.1.0   AIShell

> Get-Alias -Name Resolve-Error | Select-Object -Property Definition

Definition
----------
Resolve-AzError
```

### Expected behavior

When running `Resolve-Error`, I expect the error to be sent to the AI Shell agent for resolution.

### Actual behavior

The error information is displayed in the PowerShell window and doesn't utilize the AI.

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

0.1.0-alpha.12

### Visuals

![image](https://github.com/user-attachments/assets/ec8d9840-40cc-42b6-a48c-4ebc04822182)

**Comment by dcaro** [comment]
@wyunchi-ms PTAL

**Comment by isra-fel** [comment]
This is done as of AzPS v13.0.
