### ISSUE TITLE
Start-AIShell from PowerShell 7.4.6 open new Terminal session using Windows PowerShell

### ISSUE THREAD

**Issue by adiazcan** [PowerShell/AIShell#313]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

I don't know how to change this behavior, but I can't open pane experience on PowerShell 7. 

When I run the command Start-AIShell from a PowerShell session, it opens a new terminal with Windows PowerShell and opens the pane experience on it. 

![image](https://github.com/user-attachments/assets/f2b8b208-eb78-4430-a648-8edea099197c)

Any way to use PowerShell 7? 

### Expected behavior

```console
Opens pane experience on PowerShell 7
```

### Actual behavior

```console
Opens pane experience on a new terminal using Windows PowerShell
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

1.0.0-preview.1

**Comment by StevenBucher98** [comment]
@adiazcan do you have multiple versions of Windows Terminal installed? or are you using Terminal in elevated privileges, this may cause a new window to open and then use a default profile for the left pane which is Windows PowerShell for you.

**Comment by adiazcan** [comment]
@StevenBucher98  yes, I have multiple terminal installed. The command was opening another terminal that defaulted to Windows PowerShell.
